<?php

namespace Database\Seeders;

use App\Enums\Questionnaire\QuestionnaireQuestionIDEnum;
use App\Enums\Questionnaire\QuestionnaireQuestionSlugsEnum;
use App\Enums\Questionnaire\QuestionnaireQuestionStatusEnum;
use App\Enums\Questionnaire\QuestionnaireQuestionTypesEnum;
use App\Models\QuestionnaireQuestion;
use Illuminate\Database\Seeder;

final class QuestionnaireQuestions extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        truncate_tables([
            'questionnaire_questions',
        ]);

        foreach ($this->getQuestionData() as $question) {
            QuestionnaireQuestion::create($question);
        }
    }

    private function getQuestionData(): array
    {
        return [
            [
                'id'          => QuestionnaireQuestionIDEnum::MAIN_GOAL->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::MAIN_GOAL,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 1,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\MainGoalQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::WEIGHT_GOAL->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::WEIGHT_GOAL,
                'type'        => QuestionnaireQuestionTypesEnum::NUMBER->value,
                'order'       => 2,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\WeightGoalQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::EXTRA_GOAL->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::EXTRA_GOAL,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 3,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\ExtraGoalQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::FIRST_NAME->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::FIRST_NAME,
                'type'        => QuestionnaireQuestionTypesEnum::TEXT->value,
                'order'       => 4,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\FirstNameQuestionService',
                'is_required' => 1,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_WELCOME->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_WELCOME,
                'type'        => QuestionnaireQuestionTypesEnum::INFO_PAGE->value,
                'order'       => 5,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\InfoPage\WelcomeInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_SALES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_SALES,
                'type'        => QuestionnaireQuestionTypesEnum::SALES_PAGE->value,
                'order'       => 6,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SalesPage\SalesInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::MAIN_GOAL_REASON->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::MAIN_GOAL_REASON,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 7,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\MainGoalReasonQuestionService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::CIRCUMSTANCES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::CIRCUMSTANCES,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 8,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\CircumstancesQuestionService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::SOCIABILITY->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::SOCIABILITY,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 9,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SociabilityQuestionService',
                'is_required' => 1,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_SUPPORT->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_SUPPORT,
                'type'        => QuestionnaireQuestionTypesEnum::INFO_PAGE->value,
                'order'       => 10,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\InfoPage\SupportInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::DIFFICULTIES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::DIFFICULTIES,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 11,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\DifficultiesQuestionService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::LIFESTYLE->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::LIFESTYLE,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 12,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\LifestyleQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::DIETS->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::DIETS,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 13,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\DietsQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::MEALS_PER_DAY->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::MEALS_PER_DAY,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 14,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\MealsPerDayQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::ALLERGIES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::ALLERGIES,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 15,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\AllergiesQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::EXCLUDE_INGREDIENTS->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::EXCLUDE_INGREDIENTS,
                'type'        => QuestionnaireQuestionTypesEnum::SEARCH_SELECT->value,
                'order'       => 16,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\ExcludeIngredientsQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_SECURITY->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_SECURITY,
                'type'        => QuestionnaireQuestionTypesEnum::INFO_PAGE->value,
                'order'       => 17,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\InfoPage\SecurityInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::EMAIL->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::EMAIL,
                'type'        => QuestionnaireQuestionTypesEnum::MIXED->value,
                'order'       => 18,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\EmailQuestionService',
                'is_required' => 1,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_TESTIMONIALS->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_TESTIMONIALS,
                'type'        => QuestionnaireQuestionTypesEnum::SALES_PAGE->value,
                'order'       => 19,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SalesPage\TestimonialInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::SPORTS->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::SPORTS,
                'type'        => QuestionnaireQuestionTypesEnum::MIXED->value,
                'order'       => 20,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SportsQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::RECIPE_PREFERENCES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::RECIPE_PREFERENCES,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 21,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\RecipePreferencesQuestionService',
                'is_required' => 1,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::DISEASES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::DISEASES,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 22,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\DiseasesQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::MOTIVATION->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::MOTIVATION,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 23,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\MotivationQuestionService',
                'is_required' => 1,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_MOTIVATION->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_MOTIVATION,
                'type'        => QuestionnaireQuestionTypesEnum::INFO_PAGE->value,
                'order'       => 24,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\InfoPage\MotivationInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_TEAM_DETAILS->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_TEAM_DETAILS,
                'type'        => QuestionnaireQuestionTypesEnum::SALES_PAGE->value,
                'order'       => 25,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SalesPage\TeamDetailsInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::GENDER->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::GENDER,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 26,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\GenderQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::BIRTHDATE->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::BIRTHDATE,
                'type'        => QuestionnaireQuestionTypesEnum::DATE->value,
                'order'       => 27,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\BirthdateQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::HEIGHT->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::HEIGHT,
                'type'        => QuestionnaireQuestionTypesEnum::NUMBER->value,
                'order'       => 28,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\HeightQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::WEIGHT->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::WEIGHT,
                'type'        => QuestionnaireQuestionTypesEnum::NUMBER->value,
                'order'       => 29,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\WeightQuestionService',
                'is_required' => 1,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::FAT_CONTENT->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::FAT_CONTENT,
                'type'        => QuestionnaireQuestionTypesEnum::RADIO->value,
                'order'       => 30,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\FatContentQuestionService',
                'is_required' => 0,
                'is_editable' => 1,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::FEATURES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::FEATURES,
                'type'        => QuestionnaireQuestionTypesEnum::CHECKBOX->value,
                'order'       => 31,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\FeaturesQuestionService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_FEATURES->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_FEATURES,
                'type'        => QuestionnaireQuestionTypesEnum::SALES_PAGE->value,
                'order'       => 32,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SalesPage\FeaturesInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
            [
                'id'          => QuestionnaireQuestionIDEnum::INFO_BENEFITS->value,
                'slug'        => QuestionnaireQuestionSlugsEnum::INFO_BENEFITS,
                'type'        => QuestionnaireQuestionTypesEnum::SALES_PAGE->value,
                'order'       => 33,
                'status'      => QuestionnaireQuestionStatusEnum::ACTIVE->value,
                'service'     => 'App\Services\Questionnaire\Question\SalesPage\BenefitsInfoPageService',
                'is_required' => 0,
                'is_editable' => 0,
            ],
        ];
    }
}
