image: atlassian/default-image:4

pipelines:
  branches:
    staging:
      - step:
          name: 'staging'
          deployment: staging
          image: amazon/aws-cli
          script:
            - sh ./scripts/deployment/bitbucket-pipelines-codedeploy-staging.sh

    master:
      - step:
          name: 'aws backup'
          deployment: production backup
          image: python:3.11.2-alpine3.17
          script:
            - pip install -r ./scripts/backup/requirements.txt
            - python ./scripts/backup/aws_ec2_rds_bkps.py
      
      - step:
          name: 'production-static'
          deployment: production static
          image: amazon/aws-cli
          script:
            - sh ./scripts/deployment/bitbucket-pipelines-codedeploy-static.sh

      - step:
          name: 'production'
          deployment: production
          image: amazon/aws-cli
          script:
            - sh ./scripts/deployment/bitbucket-pipelines-codedeploy.sh
